# Wikibase with Query Service
#
# This docker-compose example can be used to pull the images from docker hub.
#
# Examples:
#
# Access Wikibase via "http://localhost:8181"
#   (or "http://$(docker-machine ip):8181" if using docker-machine)
#
# Access Query Service via "http://localhost:8282"
#   (or "http://$(docker-machine ip):8282" if using docker-machine)
#
# Access QuickStatemets via "http://localhost:9191"
#   (or "http://$(docker-machine ip):9191" if using docker-machine)
version: '3'

services:
  wikibase:
    image: ${DOCKER_REPO:-wikibase}/wikibase:1.33-bundle
    links:
      - mysql
#   ports:
    # CONFIG - Change the 8181 here to expose Wikibase & MediaWiki on a different port
#    - "8181:80"
    volumes:
      - mediawiki-images-data:/var/www/html/images
      - quickstatements-data:/quickstatements/data
    depends_on:
    - mysql
    - elasticsearch
    restart: unless-stopped
    networks:
      default:
        aliases:
         - wikibase.svc 
         # CONFIG - Add your real wikibase hostname here, for example wikibase-registry.wmflabs.org
    environment:
      - DB_SERVER=mysql.svc:3306
      - MW_ELASTIC_HOST=elasticsearch.svc
      - MW_ELASTIC_PORT=9200
      # CONFIG - Change the default values below
      - MW_ADMIN_NAME=${MW_ADMIN_NAME:-WikibaseAdmin}
      - MW_ADMIN_PASS=${MW_ADMIN_PASS:-WikibaseDockerAdminPass}
      - MW_ADMIN_EMAIL=${MW_ADMIN_EMAIL:-admin@example.com}
      - MW_WG_SECRET_KEY=${MW_WG_SECRET_KEY:-secretkey}
      # CONFIG - Change the default values below (should match mysql values in this file)
      - DB_USER=wikiuser
      - DB_PASS=sqlpass
      - DB_NAME=my_wiki
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=https://${QUICKSTMT_PUBLIC_HOST:-http://localhost:9191}
      # nginx proxy letsencrypt companion
      - VIRTUAL_HOST=${WIKIDATA_PUBLIC_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${WIKIDATA_PUBLIC_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      
  mysql:
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'sqlpass'
    networks:
      default:
        aliases:
         - mysql.svc
  wdqs-frontend:
    image: ${DOCKER_REPO:-wikibase}/wdqs-frontend:latest
    restart: unless-stopped
    # ports:
    # # CONFIG - Change the 8282 here to expose the Query Service UI on a different port
    #  - "8282:80"
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
         #- ${QUERYSVC_PUBLIC_HOST}
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs-proxy.svc
      - BRAND_TITLE=${BRAND_TITLE:-DockerWikiBase}
      # nginx proxy letsencrypt companion
      - VIRTUAL_HOST=${QUERYSVC_PUBLIC_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${QUERYSVC_PUBLIC_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  wdqs:
    image: ${DOCKER_REPO:-wikibase}/wdqs:0.3.10
    restart: unless-stopped
    volumes:
      - query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WIKIBASE_SCHEME=http
      - WIKIBASE_CONCEPT_HOST=${WIKIDATA_PUBLIC_HOST:-wikibase.svc}
      - WIKIBASE_CONCEPT_SCHEME=https
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
    expose:
      - 9999
  wdqs-proxy:
    image: ${DOCKER_REPO:-wikibase}/wdqs-proxy
    restart: unless-stopped
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    # ports:
    #  - "8989:80"
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc
  wdqs-updater:
    image: ${DOCKER_REPO:-wikibase}/wdqs:0.3.10
    restart: unless-stopped
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=wikibase.svc
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999
  elasticsearch:
    image: ${DOCKER_REPO:-wikibase}/elasticsearch:5.6.14-extra
    restart: unless-stopped
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  # CONFING, in order to not load quickstatements then remove this entire section
  quickstatements:
    image: ${DOCKER_REPO:-wikibase}/quickstatements:latest
#    ports:
#     - "9191:80"
    depends_on:
     - wikibase
    volumes:
     - quickstatements-data:/quickstatements/data
    networks:
      default:
        aliases:
         - quickstatements.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - QS_PUBLIC_SCHEME_HOST_AND_PORT=https://${QUICKSTMT_PUBLIC_HOST:-http://localhost:9191}
      - WB_PUBLIC_SCHEME_HOST_AND_PORT=https://${WIKIDATA_PUBLIC_HOST:-http://localhost:98181}
      - WIKIBASE_SCHEME_AND_HOST=https://${WIKIDATA_PUBLIC_HOST:-http://wikibase.svc}
      - WB_PROPERTY_NAMESPACE=122
      - "WB_PROPERTY_PREFIX=Property:"
      - WB_ITEM_NAMESPACE=120
      - "WB_ITEM_PREFIX=Item:"
      # nginx LE companion
      - VIRTUAL_HOST=${QUICKSTMT_PUBLIC_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${QUICKSTMT_PUBLIC_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: proxy

volumes:
  mediawiki-mysql-data:
  mediawiki-images-data:
  query-service-data:
  quickstatements-data:
